import type { CatalogEntry } from './types';

/** Curated catalogs — tags drive topic search (أفلام، علوم، فنون، …) */
export const SOURCE_CATALOGS: CatalogEntry[] = [
  {
    id: 'arabic-news',
    name: 'أخبار عربية',
    nameEn: 'Arabic News',
    description: 'وكالات وصحف إقليمية رئيسية',
    descEn: 'Major regional agencies and newspapers',
    language: 'ar',
    items: [
      { name: 'العربية', website: 'https://www.alarabiya.net', tags: ['news', 'أخبار'] },
      { name: 'سكاي نيوز عربية', website: 'https://www.skynewsarabia.com', tags: ['news', 'أخبار'] },
      { name: 'الجزيرة', website: 'https://www.aljazeera.net', tags: ['news', 'أخبار'] },
      {
        name: 'BBC عربي',
        website: 'https://www.bbc.com/arabic',
        feedUrl: 'https://feeds.bbci.co.uk/arabic/rss.xml',
        type: 'rss',
        tags: ['news', 'أخبار'],
      },
      { name: 'France 24 عربي', website: 'https://www.france24.com/ar/', tags: ['news'] },
      { name: 'رويترز', website: 'https://www.reuters.com', tags: ['news', 'wire'] },
      { name: 'الشرق الأوسط', website: 'https://aawsat.com', tags: ['news', 'أخبار'] },
      { name: 'النهار — لبنان', website: 'https://www.annahar.com', tags: ['news'] },
    ],
  },
  {
    id: 'saudi',
    name: 'سعودية',
    nameEn: 'Saudi Arabia',
    description: 'مصادر محلية في المملكة',
    descEn: 'Local sources in Saudi Arabia',
    language: 'ar',
    items: [
      { name: 'واس', website: 'https://www.spa.gov.sa', tags: ['official', 'news'] },
      { name: 'أرقام', website: 'https://www.argaam.com', tags: ['business', 'اقتصاد'] },
      { name: 'الاقتصادية', website: 'https://www.aleqt.com', tags: ['business'] },
      { name: 'سبق', website: 'https://sabq.org', tags: ['news'] },
      { name: 'عكاظ', website: 'https://www.okaz.com.sa', tags: ['news'] },
    ],
  },
  {
    id: 'entertainment',
    name: 'أفلام ومسلسلات',
    nameEn: 'Movies & Series',
    description: 'سينما، دراما، منوعات وترفيه عربي وعالمي',
    descEn: 'Cinema, drama, entertainment — Arabic & international',
    language: 'mixed',
    items: [
      {
        name: 'Variety',
        website: 'https://variety.com',
        feedUrl: 'https://variety.com/feed/',
        type: 'rss',
        tags: ['افلام', 'movies', 'entertainment', 'سينما', 'film'],
      },
      {
        name: 'Deadline Hollywood',
        website: 'https://deadline.com',
        feedUrl: 'https://deadline.com/feed/',
        type: 'rss',
        tags: ['افلام', 'movies', 'entertainment', 'hollywood'],
      },
      {
        name: 'The Hollywood Reporter',
        website: 'https://www.hollywoodreporter.com',
        feedUrl: 'https://www.hollywoodreporter.com/feed/',
        type: 'rss',
        tags: ['افلام', 'movies', 'entertainment'],
      },
      {
        name: 'BBC عربي — فن وثقافة',
        website: 'https://www.bbc.com/arabic/entertainment_and_arts',
        feedUrl: 'https://feeds.bbci.co.uk/arabic/entertainment_and_arts/rss.xml',
        type: 'rss',
        tags: ['فنون', 'ثقافة', 'افلام', 'منوعات', 'arts', 'entertainment'],
      },
      {
        name: 'الجزيرة — ثقافة',
        website: 'https://www.aljazeera.net/ebusiness/cultureandart',
        tags: ['فنون', 'ثقافة', 'منوعات', 'arts', 'culture'],
      },
      {
        name: 'سكاي نيوز — منوعات',
        website: 'https://www.skynewsarabia.com/lifestyle',
        tags: ['منوعات', 'entertainment', 'lifestyle'],
      },
      {
        name: 'Rotten Tomatoes',
        website: 'https://www.rottentomatoes.com',
        feedUrl: 'https://www.rottentomatoes.com/rss/',
        type: 'rss',
        tags: ['افلام', 'movies', 'reviews', 'سينما'],
      },
      {
        name: 'IndieWire',
        website: 'https://www.indiewire.com',
        feedUrl: 'https://www.indiewire.com/feed',
        type: 'rss',
        tags: ['افلام', 'movies', 'film', 'cinema'],
      },
    ],
  },
  {
    id: 'series-tv',
    name: 'مسلسلات وتلفزيون',
    nameEn: 'TV Series & Television',
    description: 'دراما، بث، مراجعات تلفزيونية',
    descEn: 'Drama, streaming & TV reviews',
    language: 'mixed',
    items: [
      {
        name: 'TVLine',
        website: 'https://tvline.com',
        feedUrl: 'https://tvline.com/feed/',
        type: 'rss',
        tags: ['مسلسلات', 'series', 'television', 'tv'],
      },
      {
        name: 'Collider TV',
        website: 'https://collider.com',
        feedUrl: 'https://collider.com/rss/tv.xml',
        type: 'rss',
        tags: ['مسلسلات', 'series', 'tv', 'streaming'],
      },
      {
        name: 'Digital Spy',
        website: 'https://www.digitalspy.com',
        feedUrl: 'https://www.digitalspy.com/feeds/all.xml/',
        type: 'rss',
        tags: ['مسلسلات', 'series', 'entertainment'],
      },
    ],
  },
  {
    id: 'arts-culture',
    name: 'فنون وثقافة',
    nameEn: 'Arts & Culture',
    description: 'فن، تصميم، أدب، تراث',
    descEn: 'Art, design, literature & heritage',
    language: 'mixed',
    items: [
      {
        name: 'The Guardian — Art',
        website: 'https://www.theguardian.com/artanddesign',
        feedUrl: 'https://www.theguardian.com/artanddesign/rss',
        type: 'rss',
        tags: ['فنون', 'arts', 'culture', 'ثقافة'],
      },
      {
        name: 'Hyperallergic',
        website: 'https://hyperallergic.com',
        feedUrl: 'https://hyperallergic.com/feed/',
        type: 'rss',
        tags: ['فنون', 'arts', 'art'],
      },
      {
        name: 'Artsy',
        website: 'https://www.artsy.net',
        feedUrl: 'https://www.artsy.net/rss/news',
        type: 'rss',
        tags: ['فنون', 'arts', 'culture'],
      },
      {
        name: 'BBC Culture',
        website: 'https://www.bbc.com/culture',
        feedUrl: 'https://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml',
        type: 'rss',
        tags: ['فنون', 'ثقافة', 'culture', 'arts'],
      },
    ],
  },
  {
    id: 'science',
    name: 'علوم',
    nameEn: 'Science',
    description: 'علوم، أبحاث، اكتشافات',
    descEn: 'Science, research & discoveries',
    language: 'mixed',
    items: [
      {
        name: 'Nature',
        website: 'https://www.nature.com',
        feedUrl: 'https://www.nature.com/nature.rss',
        type: 'rss',
        tags: ['علوم', 'science', 'research'],
      },
      {
        name: 'ScienceDaily',
        website: 'https://www.sciencedaily.com',
        feedUrl: 'https://www.sciencedaily.com/rss/all.xml',
        type: 'rss',
        tags: ['علوم', 'science'],
      },
      {
        name: 'Scientific American',
        website: 'https://www.scientificamerican.com',
        feedUrl: 'https://www.scientificamerican.com/feed/rss/',
        type: 'rss',
        tags: ['علوم', 'science'],
      },
      {
        name: 'Ars Technica — Science',
        website: 'https://arstechnica.com/science/',
        feedUrl: 'https://feeds.arstechnica.com/arstechnica/science',
        type: 'rss',
        tags: ['علوم', 'science', 'tech'],
      },
      {
        name: 'National Geographic',
        website: 'https://www.nationalgeographic.com',
        feedUrl: 'https://feeds.nationalgeographic.com/ng/News/News_Main',
        type: 'rss',
        tags: ['علوم', 'science', 'nature'],
      },
      {
        name: 'مجلة العلوم — Nature Arabic',
        website: 'https://www.nature.com/nature/articles?type=research-article&lang=ar',
        tags: ['علوم', 'science', 'عربي'],
      },
    ],
  },
  {
    id: 'sports',
    name: 'رياضة',
    nameEn: 'Sports',
    description: 'كرة، رياضة عالمية وعربية',
    descEn: 'Football, global & Arabic sports',
    language: 'mixed',
    items: [
      {
        name: 'ESPN',
        website: 'https://www.espn.com',
        feedUrl: 'https://www.espn.com/espn/rss/news',
        type: 'rss',
        tags: ['رياضة', 'sports'],
      },
      {
        name: 'BBC Sport',
        website: 'https://www.bbc.com/sport',
        feedUrl: 'https://feeds.bbci.co.uk/sport/rss.xml',
        type: 'rss',
        tags: ['رياضة', 'sports'],
      },
      {
        name: 'الجزيرة — رياضة',
        website: 'https://www.aljazeera.net/sport',
        tags: ['رياضة', 'sports', 'كرة'],
      },
      {
        name: 'العربية — رياضة',
        website: 'https://www.alarabiya.net/sport',
        tags: ['رياضة', 'sports'],
      },
    ],
  },
  {
    id: 'lifestyle',
    name: 'منوعات وحياة',
    nameEn: 'Lifestyle',
    description: 'لايف ستايل، سفر، صحة عامة',
    descEn: 'Lifestyle, travel & general health',
    language: 'mixed',
    items: [
      {
        name: 'BBC Travel',
        website: 'https://www.bbc.com/travel',
        feedUrl: 'https://feeds.bbci.co.uk/travel/rss.xml',
        type: 'rss',
        tags: ['سفر', 'travel', 'منوعات', 'lifestyle'],
      },
      {
        name: 'Lonely Planet',
        website: 'https://www.lonelyplanet.com',
        feedUrl: 'https://www.lonelyplanet.com/feeds/destinations.xml',
        type: 'rss',
        tags: ['سفر', 'travel', 'tourism'],
      },
      {
        name: 'Healthline',
        website: 'https://www.healthline.com',
        feedUrl: 'https://www.healthline.com/health-news/feed',
        type: 'rss',
        tags: ['صحة', 'health', 'wellness'],
      },
    ],
  },
  {
    id: 'tech',
    name: 'تقنية',
    nameEn: 'Technology',
    description: 'تقنية عربية وعالمية',
    descEn: 'Arabic & global technology',
    language: 'mixed',
    items: [
      {
        name: 'TechCrunch',
        website: 'https://techcrunch.com',
        feedUrl: 'https://techcrunch.com/feed/',
        type: 'rss',
        tags: ['tech', 'تقنية'],
      },
      {
        name: 'The Verge',
        website: 'https://www.theverge.com',
        feedUrl: 'https://www.theverge.com/rss/index.xml',
        type: 'rss',
        tags: ['tech', 'تقنية'],
      },
      {
        name: 'MIT Technology Review',
        website: 'https://www.technologyreview.com',
        feedUrl: 'https://www.technologyreview.com/feed/',
        type: 'rss',
        tags: ['tech', 'تقنية', 'science'],
      },
      {
        name: 'WIRED',
        website: 'https://www.wired.com',
        feedUrl: 'https://www.wired.com/feed/rss',
        type: 'rss',
        tags: ['tech', 'تقنية'],
      },
    ],
  },
  {
    id: 'global-en',
    name: 'عالمي — إنجليزي',
    nameEn: 'Global — English',
    description: 'مصادر عالمية متنوعة',
    descEn: 'Diverse global sources in English',
    language: 'en',
    items: [
      {
        name: 'Reuters',
        website: 'https://www.reuters.com',
        feedUrl: 'https://www.reutersagency.com/feed/',
        type: 'rss',
        tags: ['news', 'global'],
      },
      {
        name: 'AP News',
        website: 'https://apnews.com',
        feedUrl: 'https://rsshub.app/apnews/topics/apf-topnews',
        type: 'rss',
        tags: ['news', 'global'],
      },
      {
        name: 'The Guardian — World',
        website: 'https://www.theguardian.com/world',
        feedUrl: 'https://www.theguardian.com/world/rss',
        type: 'rss',
        tags: ['news', 'global'],
      },
      {
        name: 'NPR',
        website: 'https://www.npr.org',
        feedUrl: 'https://feeds.npr.org/1001/rss.xml',
        type: 'rss',
        tags: ['news', 'global', 'culture'],
      },
    ],
  },
  {
    id: 'official-wire',
    name: 'وكالات رسمية',
    nameEn: 'Official Wire Services',
    description: 'مصادر رسمية عالية الثقة',
    descEn: 'Highly trusted official sources',
    language: 'ar',
    items: [
      { name: 'واس — السعودية', website: 'https://www.spa.gov.sa', tags: ['official', 'news'] },
      { name: 'وام — الإمارات', website: 'https://wam.ae', tags: ['official', 'news'] },
      { name: 'الوطنية — مصر', website: 'https://www.youm7.com', tags: ['news'] },
    ],
  },
];

export function listCatalogs(): CatalogEntry[] {
  return SOURCE_CATALOGS.map((c) => ({
    ...c,
    items: c.items.map((i) => ({ ...i })),
  }));
}

export function getCatalog(id: string): CatalogEntry | undefined {
  return SOURCE_CATALOGS.find((c) => c.id === id);
}
